# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20161021_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 21, 12, 34, 44, 454095, tzinfo=utc)),
        ),
    ]
