# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 13:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_auto_20161021_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=60)),
                ('avatar', imagekit.models.fields.ProcessedImageField(upload_to='avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 26, 13, 16, 41, 600846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='staff_photo'),
        ),
    ]
