# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 19:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20161125_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 25, 19, 1, 54, 402813, tzinfo=utc)),
        ),
    ]
