# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 18:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20161125_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(default=-1, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(default=-1, max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 26, 18, 27, 34, 986160, tzinfo=utc)),
        ),
    ]
